### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by mikecann** [pearnaly/semantic-version#1]
I get this error when importing the lib.

![image](https://user-images.githubusercontent.com/215033/136643297-ef8f0073-d9b4-4b5c-86bd-b450aaca1796.png)

**Comment by pearnaly** [comment]
Hi @mikecann, i think it's a config problem. Your project seems to be importing the bundle javascript file, but it should be using the one in esm2015 or es5.
Is your project open source? Can I check it out?

**Comment by mikecann** [comment]
No unfortunately its not OS.. it was only doing it when running jest in Webstorm, it didnt error at runtime so I guess theres some sort of strange config going on there.

**Comment by pearnaly** [comment]
Hi @mikecann , I changed self to self || this, can you try the last version 1.0.7?
